### ISSUE TITLE
Refactor enemy attacks to the command pattern

### ISSUE THREAD

**Issue by TaylorSprankling** [KrimsonSchool/24T3_GPG215_Project_1#40]
Refactor enemy attacks to the command pattern as shown in the [notes](https://docs.google.com/document/d/1SW1YfkTMRkUCWcDt9HSJomTdGcW-JTVivmZR2RnpGKc/edit?pli=1&tab=t.w3a1yj4am0ad#heading=h.e4jgz0jsqjpu) document.
- Create basic attack script that is inherited by more advanced attacks
- Adjust weighted game object script to weighted type <T> to be used for more than just game objects
- Use this weighted script to allow enemies to use these attacks randomly according to their weights
- Also make the first attack from enemies faster and more variable as players just blitz the first few levels with no response from the enemy (see #53)

Related Issue(s)
- #61 
- #53

**Comment by Kaizenoku** [comment]
Refer to [discussion notes](https://docs.google.com/document/d/1SW1YfkTMRkUCWcDt9HSJomTdGcW-JTVivmZR2RnpGKc/edit?pli=1&tab=t.w3a1yj4am0ad#heading=h.e4jgz0jsqjpu), and [example A](https://gameprogrammingpatterns.com/command.html) / [example B](https://refactoring.guru/design-patterns/command).

**Comment by Kaizenoku** [comment]
Moved to week 11 milestone

**Comment by TaylorSprankling** [comment]
Refactor done now can work on balancing if required
