### ISSUE TITLE
Equipment stats are confusing

### ISSUE THREAD

**Issue by Kaizenoku** [KrimsonSchool/24T3_GPG215_Project_1#58]
Mentioned in feedback.
- No good way to compare stats between equipment
- All stats go red / green not individual stats
- Isn't obvious if new stats are compared to existing equipment or whole stats

Related Issue(s)
- #5 
- #43

**Comment by Kaizenoku** [comment]
Have to wait for #43 to be completed first

**Comment by KrimsonSchool** [comment]
why need wait #43 ?   

Change value -> +/- value like it was before = no confuse = epic

**Comment by Kaizenoku** [comment]
@KrimsonSchool I could do that but also I'm going to be changing it all anyways, so I'll wait until after anyways.

**Comment by KrimsonSchool** [comment]
Ok
