### ISSUE TITLE
Starting deadzone for PC is too small

### ISSUE THREAD

**Issue by Kaizenoku** [KrimsonSchool/24T3_GPG215_Project_1#59]
Not necessarily relevant as this is a mobile game, but for playtesting purposes we could add the following;

```
// Any "standalone" PC build (eg. Windows, Mac, Linux, etc.) OR web build
#if UNITY_STANDALONE || UNITY_WEBPLAYER
    deadzone = X

// Could also use "#elif UNITY_ANDROID || UNITY_IOS" for "else if"
#else
    deadzone = y
```

**Comment by TaylorSprankling** [comment]
I ended up just opting to increaing the default deadzone to 5%

now that fps on phones is set higher, the deadzone doesn't feel like it needs to be super low and can be similar to pc

If it still doesn't feel natural though yeh can open issue again and try different defaults per platform
